[tool.poetry]
name = "pybigquery-merge-into"
version = "0.1.0"
description = "Add support for bigquery's MERGE INTO feature to pybigquery"
authors = ["Martin Keogh <martin1keogh@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8, <3.10"
pybigquery = "^0.6.1"
# Major changes coming in 1.4, can't know whether it'll work with it just yet.
# Will need to try it out once pybigquery is compatible with it.
SQLAlchemy = "~1.3.24"

[tool.poetry.dev-dependencies]
pytest = "^6.2.3"
sqlparse = "^0.4.1"
mypy = "^0.812"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
