[tool.poetry]
name = "pybigquery-merge-into"
version = "0.1.0"
description = "Add support for bigquery's MERGE INTO feature to pybigquery"
authors = ["Martin Keogh <martin1keogh@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8, <3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
