---
name: python checks

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

env:
  python_version: 3.8
  poetry_version: 1.1.5
  POETRY_VIRTUALENVS_IN_PROJECT: "true"

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python_version }}

      - name: Set up poetry
        run: pip install poetry==${{ env.poetry_version }}

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3.0.11
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: poetry install
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'

      - name: Pytest unit tests
        run: poetry run pytest -v tests/unit/
